import type { CaseStudy } from './caseStudies';
import { exportAsCSV } from './exportData';

export function generateGitHubExport(study: CaseStudy) {
  // Generate README.md
  const readme = generateReadme(study);

  // Generate insights_summary.md
  const insights = generateInsightsSummary(study);

  // Generate analysis.sql
  const sql = generateSQL(study);

  // Download all files
  downloadFile(`${study.id}/README.md`, readme);
  setTimeout(() => downloadFile(`${study.id}/analysis.sql`, sql), 200);
  setTimeout(() => downloadFile(`${study.id}/insights_summary.md`, insights), 400);

  // Export sample data as CSV
  setTimeout(() => {
    const csvContent = convertToCSV(study.sampleData);
    downloadFile(`${study.id}/cleaned_dataset.csv`, csvContent);
  }, 600);
}

function generateReadme(study: CaseStudy): string {
  return `# ${study.title}

## 📋 Overview

| Field | Details |
|-------|---------|
| **Category** | ${study.category.charAt(0).toUpperCase() + study.category.slice(1)} Analytics |
| **Company** | ${study.company} |
| **Role** | ${study.role} |
| **Duration** | ${study.duration} |

## 🎯 Business Problem

${study.problemStatement}

## 📊 Dataset

${study.datasetOverview}

## 🧹 Data Cleaning

${study.cleaningProcess.map(s => '- ' + s).join('\n')}

## 📈 Key Performance Indicators

| KPI | Value | Change | Trend |
|-----|-------|--------|-------|
${study.kpis.map(k => `| ${k.name} | ${k.value} | ${k.change} | ${k.trend === 'up' ? '📈' : k.trend === 'down' ? '📉' : '➡️'} |`).join('\n')}

## 💡 Key Insights

${study.insights.map((ins, i) => `${i + 1}. ${ins}`).join('\n\n')}

## 📝 Executive Summary

${study.executiveSummary}

## ✅ Recommendations

${study.recommendations.map((rec, i) => `${i + 1}. ${rec}`).join('\n')}

## 🎯 Expected Impact

${study.impact}

## 🛠 Tools Used

${study.tools.map(t => '`' + t + '`').join(' • ')}

## 📁 Project Structure

\`\`\`
${study.id}/
├── README.md              # This file
├── analysis.sql           # SQL queries used
├── cleaned_dataset.csv    # Processed dataset
└── insights_summary.md    # Detailed findings
\`\`\`

---

*Generated by [Elite Data Analyst Lab](https://intelligence-studio.app) — Senior-Level Analytics Portfolio Platform*
`;
}

function generateInsightsSummary(study: CaseStudy): string {
  return `# ${study.title} — Insights Summary

## Executive Summary

${study.executiveSummary}

## Key Findings

${study.insights.map((ins, i) => `### Finding ${i + 1}\n\n${ins}`).join('\n\n')}

## Strategic Recommendations

${study.recommendations.map((rec, i) => `### Recommendation ${i + 1}\n\n${rec}`).join('\n\n')}

## Expected Impact

${study.impact}

## KPI Dashboard

${study.kpis.map(k => `- **${k.name}**: ${k.value} (${k.change})`).join('\n')}

---

*Analysis performed as ${study.role} at ${study.company}*
*Duration: ${study.duration}*
`;
}

function generateSQL(study: CaseStudy): string {
  return `-- ============================================
-- ${study.title}
-- ${study.role} | ${study.company}
-- ============================================

${study.sqlQueries.map(sq => `-- ${sq.title}
-- ${sq.explanation}

${sq.query}
`).join('\n\n')}
`;
}

function convertToCSV(data: Record<string, unknown>[]): string {
  if (data.length === 0) return '';
  const headers = Object.keys(data[0]);
  const rows = data.map(row => headers.map(h => {
    const val = row[h];
    const str = String(val ?? '');
    return str.includes(',') || str.includes('"') ? '"' + str.replace(/"/g, '""') + '"' : str;
  }).join(','));
  return [headers.join(','), ...rows].join('\n');
}

function downloadFile(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename.split('/').pop() || filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
